### ISSUE TITLE
Actions not triggered on Pull Requqest

### ISSUE THREAD

**Issue by RobWin** [eclipse-lmos/lmos-operator#52]
I think we need to modify all of our GitHub Workflow files. They are not triggered for Pull Requests
Instead of

```
on: [ push ]
 ```

it should be

```
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
```

**Comment by kaikreuzer** [comment]
I noticed that as well today on a few PRs. It actually worked so far, because PRs were only done by committers and they pushed the branches not to their forks, but to this repo itself - therefore [the checks were triggered](https://github.com/eclipse-lmos/lmos-operator/pull/41/checks). To still allow committers to push branches to this repo, I would suggest to adapt the workflow trigger definition to
```
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
 ```
Does this make sense?
